FROM n8nio/n8n:latest

USER root

EXPOSE 3000

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=3000
ENV N8N_PROTOCOL=https
ENV NODE_ENV=production
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

WORKDIR /home/node/.n8n

ENTRYPOINT ["n8n"]
CMD ["start"]